export const FETCH_BANK_CARDS = "FETCH_BANK_CARDS";
export const FLIP_BANK_CARD = "FLIP_BANK_CARD";
export const UNFLIP_BANK_CARD = "UNFLIP_BANK_CARD";
export const GET_DEBIT_CARDS = "GET_DEBIT_CARDS";
export const GET_DEBIT_CARDS_FAILED = "GET_DEBIT_CARDS_FAILED";
