export const CREATE_TUDO_CREATING = "CREATE_TUDO_LOADING";
export const CREATE_TUDO_SUCCESS = "CREATE_TUDO_SUCCESS";
export const CREATE_TUDO_FAIL = "CREATE_TUDO_FAIL";
export const GET_TUDO_SUCCESS = "GET_TUDO_SUCCESS";
export const GET_TUDO_LOADING = "GET_TUDO_LOADING";
export const GET_TUDO_FAIL = "GET_TUDO_FAIL";
export const CLOSE_MODAL = "CLOSE_MODAL";
export const UPDATE_TUDO_VISIBILITY_SUCCESS = "UPDATE_TUDO_VISIBILITY_SUCCESS";
export const UPDATE_TUDO_VISIBILITY_FAIL = "UPDATE_TUDO_VISIBILITY_FAIL";
export const UPDATE_TUDO_VISIBILITY_UPDATING =
  "UPDATE_TUDO_VISIBILITY_UPDATING";
export const TOP_UP_TODO = "TOP_UP_TODO";
export const TOP_UP_TODO_SUCCESS = "TOP_UP_TODO_SUCCESS";
export const TOP_UP_TODO_FAIL = "TOP_UP_TODO_FAIL";
export const WITHDRAW_TODO = "WITHDRAW_TODO";
export const WITHDRAW_TODO_SUCCESS = "WITHDRAW_TODO_SUCCESS";
export const WITHDRAW_TODO_FAIL = "WITHDRAW_TODO_FAIL";
