export const CREATE_TUDO_CREATING = "CREATE_TUDO_LOADING";
export const CREATE_TUDO_SUCCESS = "CREATE_TUDO_SUCCESS";
export const CREATE_TUDO_FAIL = "CREATE_TUDO_FAIL";
export const GET_TUDO_SUCCESS = "GET_TUDO_SUCCESS";
export const GET_TUDO_LOADING = "GET_TUDO_LOADING";
export const GET_TUDO_FAIL = "GET_TUDO_FAIL";
export const CLOSE_MODAL = "CLOSE_MODAL";
