export const CREATE_TARGET_CREATING = "CREATE_TARGET_LOADING";
export const CREATE_TARGET_SUCCESS = "CREATE_TARGET_SUCCESS";
export const CREATE_TARGET_FAIL = "CREATE_TARGET_FAIL";
export const GET_SAVINGS_SUCCESS = "GET_SAVINGS_SUCCESS";
export const GET_SAVINGS_FAIL = "GET_SAVINGS_FAIL";
export const GET_SAVINGS_LOADING = "GET_SAVINGS_LOADING";
