export const FETCH_BANK_ACCOUNTS = "FETCH_BANK_ACCOUNTS ";
export const ADD_BANK_ACCOUNT = "ADD_BANK_ACCOUNT";
export const DELETE_BANK_ACCOUNT = "DELETE_BANK_ACCOUNT";
export const FLIP_CARD = "FLIP_CARD";
export const UNFLIP_CARD = "UNFLIP_CARD";
